"""
Association Rules Page
Market basket analysis with product recommendations and bundle insights.
Supports Boss Mode for executive view.
"""

import streamlit as st
import pandas as pd
from pathlib import Path

import sys
sys.path.append(str(Path(__file__).parent.parent))

from config import ASSOCIATION_RULES, REPORTS_PATH, BOSS_BUNDLES
from components.charts import scatter_chart, bar_chart

# Check Boss Mode
boss_mode = st.session_state.get("boss_mode", False)

# Convert rules to DataFrame
rules_df = pd.DataFrame(ASSOCIATION_RULES)

# =============================================================================
# BOSS MODE VIEW
# =============================================================================
if boss_mode:
    st.title("Profitable Bundles")
    st.markdown("### *Which products to sell together to increase basket size?*")

    st.markdown("---")

    # Big number - Real ROI from notebook 08
    st.markdown("""
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 15px; text-align: center; color: white; margin-bottom: 20px;">
        <h1 style="margin: 0; font-size: 4em;">5,378€</h1>
        <p style="font-size: 1.3em; margin: 10px 0;">validated net profit from bundle promotions</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("---")

    # Top 5 Bundles
    st.subheader("Top 5 Bundles to Promote")

    for i, bundle in enumerate(BOSS_BUNDLES[:5], 1):
        col1, col2, col3 = st.columns([0.5, 3, 1.5])

        with col1:
            st.markdown(f"### {i}.")

        with col2:
            st.markdown(f"**{bundle['bundle']}**")
            st.caption(bundle['why'])

        with col3:
            st.markdown(f"""
            <div style="background-color: #d4edda; padding: 10px; border-radius: 8px; text-align: center;">
                <span style="color: #155724; font-weight: bold; font-size: 1.5em;">{bundle['gain']}</span>
                <br><small>sales lift</small>
            </div>
            """, unsafe_allow_html=True)

        if i < 5:
            st.markdown("---")

    st.markdown("---")

    # Action Plan
    st.subheader("How to Use These Bundles")

    st.markdown("""
    | Action | How | Expected Result |
    |--------|-----|-----------------|
    | **10% Discount** | Standard replenishment items | +15% purchase probability |
    | **20% Discount** | High-discovery products (lift > 10) | +35% purchase probability |
    | **Timing** | Send promo at 80% of repurchase cycle | Optimal conversion |
    | **GO/NO GO** | Block promos where discount > margin | Avoid losses |
    """)

    st.markdown("---")

    # ROI Results (from notebook 08_business_impact_ROI)
    st.subheader("ROI Results")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Net Profit", "5,378€", help="Validated promotional campaigns")
    with col2:
        st.metric("Avoided Losses", "174€", help="Blocked unprofitable promos")
    with col3:
        st.metric("Personalized Offers", "50,649", help="Generated by prediction engine")

    st.markdown("---")
    st.caption("Switch to Analyst mode for technical metrics (lift, confidence, support)")

# =============================================================================
# ANALYST MODE VIEW
# =============================================================================
else:
    st.title("Association Rules")
    st.markdown("Discover **product associations** and bundle recommendations from market basket analysis.")

    st.markdown("---")

    # Metrics
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Total Rules", len(rules_df))
    with col2:
        st.metric("Avg Confidence", f"{rules_df['confidence'].mean():.1%}")
    with col3:
        st.metric("Avg Lift", f"{rules_df['lift'].mean():.2f}")
    with col4:
        st.metric("Max Lift", f"{rules_df['lift'].max():.2f}")

    st.markdown("---")

    # Filters
    st.subheader("Filter Rules")

    col1, col2 = st.columns(2)

    with col1:
        min_confidence = st.slider(
            "Minimum Confidence",
            min_value=0.0,
            max_value=0.5,
            value=0.2,
            step=0.05
        )

    with col2:
        min_lift = st.slider(
            "Minimum Lift",
            min_value=1.0,
            max_value=3.0,
            value=1.5,
            step=0.1
        )

    # Product search
    products_in_rules = list(set(rules_df["antecedent"].tolist() + rules_df["consequent"].tolist()))
    search_product = st.selectbox(
        "Filter by Product",
        options=["All Products"] + sorted(products_in_rules)
    )

    # Apply filters
    filtered_rules = rules_df[
        (rules_df["confidence"] >= min_confidence) &
        (rules_df["lift"] >= min_lift)
    ]

    if search_product != "All Products":
        filtered_rules = filtered_rules[
            (filtered_rules["antecedent"] == search_product) |
            (filtered_rules["consequent"] == search_product)
        ]

    st.markdown("---")

    # Rules Table
    st.subheader("Association Rules")

    if not filtered_rules.empty:
        # Format for display
        display_df = filtered_rules.copy()
        display_df["Rule"] = display_df["antecedent"] + " -> " + display_df["consequent"]
        display_df["Confidence"] = display_df["confidence"].apply(lambda x: f"{x:.1%}")
        display_df["Lift"] = display_df["lift"].apply(lambda x: f"{x:.2f}")
        display_df["Support"] = display_df["support"].apply(lambda x: f"{x:.2%}")

        st.dataframe(
            display_df[["Rule", "Support", "Confidence", "Lift"]].sort_values("Lift", ascending=False),
            use_container_width=True,
            hide_index=True
        )

        st.caption(f"Showing {len(filtered_rules)} rules matching your filters.")
    else:
        st.warning("No rules match the current filters. Try adjusting the thresholds.")

    st.markdown("---")

    # Visualization
    st.subheader("Rule Visualization")

    col1, col2 = st.columns(2)

    with col1:
        # Confidence vs Lift scatter
        fig_scatter = scatter_chart(
            data=rules_df,
            x_col="confidence",
            y_col="lift",
            size_col="support",
            hover_name="antecedent",
            title="Confidence vs Lift (size = support)"
        )
        st.plotly_chart(fig_scatter, use_container_width=True)

    with col2:
        # Top rules by lift
        top_rules = rules_df.nlargest(10, "lift").copy()
        top_rules["rule"] = top_rules["antecedent"] + " -> " + top_rules["consequent"]

        fig_bar = bar_chart(
            data=top_rules,
            x_col="rule",
            y_col="lift",
            title="Top 10 Rules by Lift",
            color="confidence",
            orientation="h"
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    st.markdown("---")

    # Bundle Recommendations
    st.subheader("Bundle Recommendations")

    st.markdown("""
    Based on the association rules, here are **strategic bundle recommendations**:
    """)

    # Group recommendations by consequent
    banana_rules = rules_df[rules_df["consequent"].str.contains("Banana", case=False)]
    organic_rules = rules_df[rules_df["antecedent"].str.contains("Organic", case=False)]

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("#### Banana Bundles")
        st.markdown("Products frequently bought with bananas:")

        if not banana_rules.empty:
            for _, rule in banana_rules.head(5).iterrows():
                st.markdown(f"- **{rule['antecedent']}** (Lift: {rule['lift']:.2f})")
        else:
            st.info("No banana-related rules found.")

    with col2:
        st.markdown("#### Organic Bundles")
        st.markdown("Organic products with strong associations:")

        if not organic_rules.empty:
            for _, rule in organic_rules.head(5).iterrows():
                st.markdown(f"- **{rule['antecedent']}** -> {rule['consequent']} (Lift: {rule['lift']:.2f})")
        else:
            st.info("No organic-related rules found.")

    st.markdown("---")

    # Show report images
    st.subheader("Bundle Analysis Reports")

    reports_path = Path(__file__).parent.parent / REPORTS_PATH

    bundle_images = [
        "concrete_bundle_recommendations.png",
        "bundle_optimization_nutriscore.png"
    ]

    cols = st.columns(2)
    for idx, img_name in enumerate(bundle_images):
        img_path = reports_path / img_name
        if img_path.exists():
            with cols[idx]:
                st.image(str(img_path), caption=img_name.replace("_", " ").replace(".png", "").title())

    st.markdown("---")

    # Interpretation
    st.subheader("How to Interpret")

    st.markdown("""
    | Metric | Interpretation |
    |--------|----------------|
    | **Support** | % of transactions containing both items |
    | **Confidence** | P(consequent | antecedent) - likelihood of buying B given A |
    | **Lift** | How much more likely to buy B given A vs baseline. Lift > 1 = positive association |

    **Business Actions:**
    - **High Lift Rules**: Use for product placement and cross-selling
    - **High Confidence Rules**: Target for bundle discounts
    - **High Support Rules**: Volume-based promotional campaigns
    """)

    st.markdown("---")
    st.caption("Association rules generated using FP-Growth algorithm with min_support=0.01, min_confidence=0.2")
